# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='formatted_address',
            field=models.CharField(default='Formatted', max_length=255),
            preserve_default=False,
        ),
    ]
